using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using System;
using System.Windows.Forms;

namespace DifficultyForm
{
    // The main DifficultyForm class.
    public partial class DifficultyForm : Form
    {
        // Constructor for DifficultyForm.
        public DifficultyForm()
        {
            // Call InitializeComponent, a method generated by the Windows Forms designer.
            InitializeComponent();
        }

        // Method to open the GridForm with a specified grid size.
        private void OpenGridForm(int gridSize)
        {
            // Create a new instance of GridForm with the specified grid size.
            GridForm gridForm = new GridForm(gridSize);

            // Hide the current form.
            this.Hide();

            // Show the GridForm as a modal dialog.
            gridForm.ShowDialog();

            // After the GridForm is closed, show the current form again.
            this.Show();
        }

        // Event handler for the Click event of the "Play Game" button.
        private void button_PlayGame_Click(object sender, EventArgs e)
        {
            // Initialize the grid size to 0.
            int gridSize = 0;

            // Check which radio button is selected and set the grid size accordingly.
            if (radioButton_Easy.Checked)
            {
                gridSize = 5;
            }
            else if (radioButton_Moderate.Checked)
            {
                gridSize = 10;
            }
            else if (radioButton_Difficult.Checked)
            {
                gridSize = 20;
            }

            // Open the GridForm with the selected grid size.
            OpenGridForm(gridSize);
        }
    }
}